import fs from 'node:fs';
import path from 'node:path';
import type {LoadContext, Plugin} from '@docusaurus/types';

/**
 * Generates LLM-friendly artifacts alongside the static build, following
 * the llms.txt convention (https://llmstxt.org/):
 *
 *   /llms.txt        - index of all doc pages with links to markdown versions
 *   /llms-full.txt   - every doc page concatenated into one markdown file
 *   /<page>.md       - raw markdown mirror of each doc page
 *                      (the homepage mirrors to /index.html.md per the spec)
 *
 * The page list comes from the docs plugin's loaded content, so it stays in
 * sync with whatever the docs plugin actually built - regardless of the docs
 * path, sidebar shape (autogenerated, category links), or file extension.
 */

type LoadedDoc = {
  id: string;
  title: string;
  description?: string;
  permalink: string;
  source: string;
};

type SidebarItem = {
  type?: string;
  id?: string;
  items?: SidebarItem[];
  link?: {type?: string; id?: string};
};

function stripFrontmatter(raw: string): string {
  const match = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
  return (match ? raw.slice(match[0].length) : raw).trim();
}

/** Doc ids in sidebar order, including docs linked from categories. */
function flattenSidebarDocIds(items: readonly SidebarItem[]): string[] {
  return items.flatMap((item) => [
    ...(item.id && (item.type === 'doc' || item.type === 'ref')
      ? [item.id]
      : []),
    ...(item.link?.type === 'doc' && item.link.id ? [item.link.id] : []),
    ...(Array.isArray(item.items) ? flattenSidebarDocIds(item.items) : []),
  ]);
}

export default function llmsTxtPlugin(context: LoadContext): Plugin {
  return {
    name: 'llms-txt',

    async postBuild({outDir, plugins}) {
      const {url, baseUrl, title, tagline} = context.siteConfig;
      const siteUrl = url + baseUrl;

      const docsPlugin = plugins.find(
        (plugin) => plugin.name === 'docusaurus-plugin-content-docs',
      );
      if (!docsPlugin) {
        throw new Error('llms-txt: docs plugin content not found');
      }
      const {loadedVersions} = docsPlugin.content as {
        loadedVersions: {
          docs: LoadedDoc[];
          sidebars: Record<string, SidebarItem[]>;
        }[];
      };

      const sidebarOrder = new Map(
        loadedVersions
          .flatMap((version) =>
            Object.values(version.sidebars).flatMap(flattenSidebarDocIds),
          )
          .map((id, rank) => [id, rank]),
      );
      const rank = (doc: {id: string}) =>
        sidebarOrder.get(doc.id) ?? Number.MAX_SAFE_INTEGER;

      const docs = loadedVersions
        .flatMap((version) => version.docs)
        .sort((a, b) => rank(a) - rank(b))
        .map((doc) => {
          const raw = fs.readFileSync(
            doc.source.replace(/^@site/, context.siteDir),
            'utf8',
          );
          // Site-relative page path without leading slash; '' for the homepage.
          const pagePath = doc.permalink
            .slice(baseUrl.length)
            .replace(/\/$/, '');
          return {
            title: doc.title,
            description: doc.description ?? '',
            body: stripFrontmatter(raw),
            pagePath,
            // The llms.txt spec appends .md to the page URL, and uses
            // index.html.md for URLs that end in a bare directory path.
            mirrorFile: pagePath === '' ? 'index.html.md' : `${pagePath}.md`,
          };
        });

      // Raw markdown mirrors next to each page.
      for (const doc of docs) {
        const mirrorPath = path.resolve(outDir, doc.mirrorFile);
        if (!mirrorPath.startsWith(path.resolve(outDir) + path.sep)) {
          throw new Error(
            `llms-txt: mirror path escapes the build dir: ${doc.mirrorFile}`,
          );
        }
        fs.mkdirSync(path.dirname(mirrorPath), {recursive: true});
        fs.writeFileSync(mirrorPath, doc.body + '\n');
      }

      const index = [
        `# ${title}`,
        '',
        `> ${tagline}. Wallet management, transaction signing with automatic PoW, and real-time WebSocket subscriptions for Node.js and browsers.`,
        '',
        'The full documentation is also available as a single file at ' +
          `${siteUrl}llms-full.txt`,
        '',
        '## Documentation',
        '',
        ...docs.map(
          (doc) =>
            `- [${doc.title}](${siteUrl}${doc.mirrorFile}): ${doc.description}`,
        ),
        '',
        '## Optional',
        '',
        '- [GitHub repository](https://github.com/digitalSloth/znn-typescript-sdk): source code, issues and releases',
        '- [npm package](https://www.npmjs.com/package/znn-typescript-sdk): published releases',
        '- [Zenon Network](https://zenon.network): the Network of Momentum',
        '',
      ].join('\n');
      fs.writeFileSync(path.join(outDir, 'llms.txt'), index);

      const full = [
        `# ${title} — Full Documentation`,
        '',
        `> ${tagline}`,
        '',
        ...docs.flatMap((doc) => [
          '---',
          '',
          `<!-- Source: ${siteUrl}${doc.pagePath} -->`,
          '',
          doc.body,
          '',
        ]),
      ].join('\n');
      fs.writeFileSync(path.join(outDir, 'llms-full.txt'), full);
    },
  };
}
